In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import jaxquantum as jqt
from jax import jit

/opt/miniconda3/envs/jax-framework/lib/python3.9/site-packages/qutip/__init__.py:66: UserWarning: The new version of Cython, (>= 3.0.0) is not supported.
  warnings.warn(


In [3]:
a = jqt.Qarray.create(jqt.tensor(jqt.sigmax(),jqt.sigmax()), dims=[[2,2], [2,2]])
b = jqt.Qarray.create(jqt.tensor(jqt.sigmax(), jqt.identity(2)), dims=[[2,2], [2,2]])
a @ b

Quantum array: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper
Qarray data =
[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]

In [7]:
@jit
def test(input_a):
    b = jqt.Qarray.create(jqt.tensor(jqt.sigmax(), jqt.identity(2)), dims=[[2,2], [2,2]])
    return input_a @ b

In [9]:
%timeit test(a)

5.1 µs ± 57.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [11]:
%timeit a.data @ b.data

4.1 µs ± 52.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [2]:
import qutip as qt

/opt/miniconda3/envs/jax-framework/lib/python3.9/site-packages/qutip/__init__.py:66: UserWarning: The new version of Cython, (>= 3.0.0) is not supported.
  warnings.warn(


In [3]:
qt.tensor(qt.coherent(10,1),qt.coherent(10,1))

Quantum object: dims = [[10, 10], [1, 1]], shape = (100, 1), type = ket
Qobj data =
[[3.67879441e-01]
 [3.67879441e-01]
 [2.60130047e-01]
 [1.50186155e-01]
 [7.50930613e-02]
 [3.35827506e-02]
 [1.37094277e-02]
 [5.18515195e-03]
 [1.81760459e-03]
 [6.67227779e-04]
 [3.67879441e-01]
 [3.67879441e-01]
 [2.60130047e-01]
 [1.50186155e-01]
 [7.50930613e-02]
 [3.35827506e-02]
 [1.37094277e-02]
 [5.18515195e-03]
 [1.81760459e-03]
 [6.67227779e-04]
 [2.60130047e-01]
 [2.60130047e-01]
 [1.83939720e-01]
 [1.06197648e-01]
 [5.30988128e-02]
 [2.37465906e-02]
 [9.69402930e-03]
 [3.66645610e-03]
 [1.28524053e-03]
 [4.71801286e-04]
 [1.50186155e-01]
 [1.50186155e-01]
 [1.06197648e-01]
 [6.13132417e-02]
 [3.06566143e-02]
 [1.37101007e-02]
 [5.59685050e-03]
 [2.11682944e-03]
 [7.42033975e-04]
 [2.72394603e-04]
 [7.50930613e-02]
 [7.50930613e-02]
 [5.30988128e-02]
 [3.06566143e-02]
 [1.53283038e-02]
 [6.85504886e-03]
 [2.79842465e-03]
 [1.05841449e-03]
 [3.71016908e-04]
 [1.36197272e-04]
 [3.35827506e-02

In [11]:
a = qt.coherent(10,1)
qt.Dimensions()

AttributeError: module 'qutip' has no attribute 'Dimensions'

In [9]:
import jax.numpy as jnp
a = jnp.array([1,2])
a.size

2