In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import jaxquantum as jqt
import jax.numpy as jnp

In [9]:
jqt.Qarray.from_list([jqt.destroy(5),jqt.destroy(5)])

Quantum array: dims = ((5,), (5,)), bdims = (2,), shape = (2, 5, 5), type = oper
Qarray data =
[[[0.        +0.j 1.        +0.j 0.        +0.j 0.        +0.j
   0.        +0.j]
  [0.        +0.j 0.        +0.j 1.41421356+0.j 0.        +0.j
   0.        +0.j]
  [0.        +0.j 0.        +0.j 0.        +0.j 1.73205081+0.j
   0.        +0.j]
  [0.        +0.j 0.        +0.j 0.        +0.j 0.        +0.j
   2.        +0.j]
  [0.        +0.j 0.        +0.j 0.        +0.j 0.        +0.j
   0.        +0.j]]

 [[0.        +0.j 1.        +0.j 0.        +0.j 0.        +0.j
   0.        +0.j]
  [0.        +0.j 0.        +0.j 1.41421356+0.j 0.        +0.j
   0.        +0.j]
  [0.        +0.j 0.        +0.j 0.        +0.j 1.73205081+0.j
   0.        +0.j]
  [0.        +0.j 0.        +0.j 0.        +0.j 0.        +0.j
   2.        +0.j]
  [0.        +0.j 0.        +0.j 0.        +0.j 0.        +0.j
   0.        +0.j]]]

In [6]:
a = jqt.destroy(5)
a_dag = jqt.create(5)

evals, evecs = ((jnp.array([1, 2, 3]) * a_dag) @ a).eigenstates()

evecs[0]

Quantum array: dims = ((5,), (1,)), bdims = (5,), shape = (5, 5, 1), type = ket
Qarray data =
[[[1.+0.j]
  [0.+0.j]
  [0.+0.j]
  [0.+0.j]
  [0.+0.j]]

 [[0.+0.j]
  [1.+0.j]
  [0.+0.j]
  [0.+0.j]
  [0.+0.j]]

 [[0.+0.j]
  [0.+0.j]
  [1.+0.j]
  [0.+0.j]
  [0.+0.j]]

 [[0.+0.j]
  [0.+0.j]
  [0.+0.j]
  [1.+0.j]
  [0.+0.j]]

 [[0.+0.j]
  [0.+0.j]
  [0.+0.j]
  [0.+0.j]
  [1.+0.j]]]

In [17]:
jqt.collapse(jqt.displace(5, jnp.array([[1.0,2.0],[3.4,2.1],[3.4,2.1]])))

Quantum array: dims = ((5,), (5,)), bdims = (), shape = (5, 5), type = oper
Qarray data =
[[ 1.94704885+0.j  0.09778716+0.j  3.01646028+0.j -0.18405274+0.j
   3.1353332 +0.j]
 [-0.09778716+0.j -2.31887019+0.j  0.45708063+0.j -1.04600392+0.j
  -0.36810548+0.j]
 [ 3.01646028+0.j -0.45708063+0.j  1.09517727+0.j  0.95024198+0.j
   0.73774243+0.j]
 [ 0.18405274+0.j -1.04600392+0.j -0.95024198+0.j -0.61075294+0.j
   0.79668806+0.j]
 [ 3.1353332 +0.j  0.36810548+0.j  0.73774243+0.j -0.79668806+0.j
   0.02815075+0.j]]

In [14]:
a = jqt.displace(3, jnp.array([1.0,2.0]))
b = jqt.displace(4, jnp.array([3.0,3.0]))

# (jnp.einsum("...ij,...kl->...ikjl", a, b).reshape(*b.shape[:-2], a.shape[-2] * b.shape[-2], -1)).shape
jqt.tensor(a,b)

Quantum array: dims = ((3, 4), (3, 4)), bdims = (4,), shape = (4, 12, 12), type = oper
Qarray data =
[[[-0.29698446+0.j -0.4142589 +0.j -0.24089817+0.j -0.24105626+0.j
    0.2760176 +0.j  0.38501257+0.j  0.22389096+0.j  0.22403789+0.j
   -0.26498945+0.j -0.36962957+0.j -0.2149455 +0.j -0.21508656+0.j]
  [ 0.4142589 +0.j  0.043697  +0.j -0.16832887+0.j -0.41724786+0.j
   -0.38501257+0.j -0.04061202+0.j  0.15644499+0.j  0.38779051+0.j
    0.36962957+0.j  0.03898939+0.j -0.1501943 +0.j -0.37229652+0.j]
  [-0.24089817+0.j  0.16832887+0.j  0.38437845+0.j -0.37661243+0.j
    0.22389096+0.j -0.15644499+0.j -0.35724165+0.j  0.35002391+0.j
   -0.2149455 +0.j  0.1501943 +0.j  0.34296823+0.j -0.33603887+0.j]
  [ 0.24105626+0.j -0.41724786+0.j  0.37661243+0.j  0.043697  +0.j
   -0.22403789+0.j  0.38779051+0.j -0.35002391+0.j -0.04061202+0.j
    0.21508656+0.j -0.37229652+0.j  0.33603887+0.j  0.03898939+0.j]
  [-0.2760176 +0.j -0.38501257+0.j -0.22389096+0.j -0.22403789+0.j
    0.07776721+0.j  0.10

In [5]:
jqt.displace(3,jnp.array([1,2])) ^ jqt.displace(3,jnp.array([1.1,2]))

Quantum array: dims = ((3, 3), (3, 3)), bdims = (4,), shape = (4, 9, 9), type = oper
Qarray data =
[[[ 0.34167484+0.j -0.3343851 +0.j  0.38392077+0.j -0.31755288+0.j
    0.31077779+0.j -0.35681629+0.j  0.3048652 +0.j -0.29836081+0.j
    0.34255986+0.j]
  [ 0.3343851 +0.j -0.20127112+0.j -0.47289194+0.j -0.31077779+0.j
    0.18706155+0.j  0.43950617+0.j  0.29836081+0.j -0.17958759+0.j
   -0.4219459 +0.j]
  [ 0.38392077+0.j  0.47289194+0.j  0.07020186+0.j -0.35681629+0.j
   -0.43950617+0.j -0.06524567+0.j  0.34255986+0.j  0.4219459 +0.j
    0.06263881+0.j]
  [ 0.31755288+0.j -0.31077779+0.j  0.35681629+0.j -0.08946966+0.j
    0.0875608 +0.j -0.10053202+0.j -0.44908759+0.j  0.43950617+0.j
   -0.50461443+0.j]
  [ 0.31077779+0.j -0.18706155+0.j -0.43950617+0.j -0.0875608 +0.j
    0.05270408+0.j  0.12382967+0.j -0.43950617+0.j  0.26454498+0.j
    0.62155559+0.j]
  [ 0.35681629+0.j  0.43950617+0.j  0.06524567+0.j -0.10053202+0.j
   -0.12382967+0.j -0.01838279+0.j -0.50461443+0.j -0.62155559+0

In [43]:
jnp.kron(jqt.displace(3,jnp.array([1,2])).data, jqt.displace(5,jnp.array([1,3.4])).data).shape

(4, 15, 15)

In [33]:
jqt.displace(4,4) ^ jqt.displace(3,1)

NameError: name 'QarrayArray' is not defined

In [21]:
a = jnp.array([
    [[1],[2],[3]],
    [[5],[2],[3]]
])

a_qt = jqt.Qarray.create(a)
a_qt.data, 1/a_qt.data

(Array([[[1.+0.j],
         [2.+0.j],
         [3.+0.j]],
 
        [[5.+0.j],
         [2.+0.j],
         [3.+0.j]]], dtype=complex128, weak_type=True),
 Array([[[1.        +0.j],
         [0.5       +0.j],
         [0.33333333+0.j]],
 
        [[0.2       +0.j],
         [0.5       +0.j],
         [0.33333333+0.j]]], dtype=complex128, weak_type=True))

In [14]:
alphas = jnp.array([[0.1,0.2,0.3],[0.4,0.5,0.6]])
ds = jqt.displace(10, alphas)
ds

Quantum array: dims = ((10,), (10,)), bdims = (2, 3), shape = (2, 3, 10, 10), type = oper
Qarray data =
[[[[ 9.95012479e-01+0.j -9.95012479e-02+0.j  7.03580071e-03+0.j
    -4.06212144e-04+0.j  2.03106072e-05+0.j -9.08317966e-07+0.j
     3.70819257e-08+0.j -1.40156505e-09+0.j  4.95527700e-11+0.j
    -1.65326214e-12+0.j]
   [ 9.95012479e-02+0.j  9.85062354e-01+0.j -1.40012434e-01+0.j
     1.21457431e-02+0.j -8.10393227e-04+0.j  4.53250665e-05+0.j
    -2.22120735e-06+0.j  9.79693971e-08+0.j -3.95926482e-09+0.j
     1.48658310e-10+0.j]
   [ 7.03580071e-03+0.j  1.40012434e-01+0.j  9.75161980e-01+0.j
    -1.70620677e-01+0.j  1.71193712e-02+0.j -1.27813923e-03+0.j
     7.83482550e-05+0.j -4.14857097e-06+0.j  1.95658481e-07+0.j
    -8.40003804e-09+0.j]
   [ 4.06212144e-04+0.j  1.21457431e-02+0.j  1.70620677e-01+0.j
     9.65311191e-01+0.j -1.96027400e-01+0.j  2.20272197e-02+0.j
    -1.80303840e-03+0.j  1.19439419e-04+0.j -6.76327146e-06+0.j
     3.39011810e-07+0.j]
   [ 2.03106072e-05+0.j  8.1

In [16]:
a = jnp.array([
    [[1],[2],[3]],
    [[5],[2],[3]]
])

b = jnp.array([1,2,3])

# a = jnp.array([1,2,3])
a_jqt = jqt.Qarray.create(a)
a_jqt

b_jqt = jqt.Qarray.create(b)

In [13]:
 b_jqt.to_dm() @ a_jqt

Quantum array: dims = [(3,), (1,)], bdims = (2,), shape = (2, 3, 1), type = ket
Qarray data =
[[[14.+0.j]
  [28.+0.j]
  [42.+0.j]]

 [[18.+0.j]
  [36.+0.j]
  [54.+0.j]]]

In [22]:
a_jqt.data * b_jqt.to_dm().data

Array([[[ 1.+0.j,  2.+0.j,  3.+0.j],
        [ 4.+0.j,  8.+0.j, 12.+0.j],
        [ 9.+0.j, 18.+0.j, 27.+0.j]],

       [[ 5.+0.j, 10.+0.j, 15.+0.j],
        [ 4.+0.j,  8.+0.j, 12.+0.j],
        [ 9.+0.j, 18.+0.j, 27.+0.j]]], dtype=complex128, weak_type=True)